const HomeButton = document.getElementById("HomeButton");
const TimerCount = document.getElementById("Time1");
const ReadButton = document.getElementById("ReadAboutButton");
const ContactButton = document.getElementById("ContactUsButton");
const NewGameButton = document.getElementById("NewGame");
const ResetGameButton = document.getElementById("ResetGame");
const Box = document.getElementById("one");
const Box2 = document.getElementById("second");
const Box3 = document.getElementById("three");
const Box4 = document.getElementById("four");
const Box5 = document.getElementById("five");
const Box6 = document.getElementById("six");
const Box7 = document.getElementById("seven");
const Box8 = document.getElementById("Eight");
const Box9 = document.getElementById("Nine");
const Box10 = document.getElementById("Ten");
const Box11 = document.getElementById("Eleven");
const Box12 = document.getElementById("Twelve");
const Start_Over = document.getElementById("startEnd");
const RuleOne = document.getElementById("RUle1");
const RuleTwo = document.getElementById("Rule2")


setInterval(()=>{
    let d = new Date();
    TimerCount.innerText = d.toLocaleTimeString();
},1000);

NewGameButton.addEventListener("click", () => {
   NewGameFunc();
});

HomeButton.addEventListener("click",()=>{
    NewGameFunc();
})

function NewGameFunc( Num){
    GenerateNum();
    Start_Over.innerText = " The game has started !"
    RuleOne.innerText = "Note : Choose Numbers Between 1 to 12 Numbers in the Box"
    RuleTwo.innerText = "Number Are Generated By Computer"
    RuleOne.style.color = "black"
    RuleOne.style.fontSize = "1em";
    RuleTwo.style.color = "black"
    RuleTwo.style.fontSize = "1em";
     Box.style.color = "black";
    Box2.style.color = "black";
    Box3.style.color = "black";
    Box4.style.color = "black";
    Box5.style.color = "black";
    Box6.style.color = "black";
    Box7.style.color = "black";
    Box8.style.color = "black";
    Box9.style.color = "black";
   Box10.style.color = "black";
   Box11.style.color = "black";
   Box12.style.color = "black";
     Box.style.backgroundcolor = "black";
    Box2.style.backgroundcolor = "black";
    Box3.style.backgroundcolor = "black";
    Box4.style.backgroundcolor = "black";
    Box5.style.backgroundcolor = "black";
    Box6.style.backgroundcolor = "black";
    Box7.style.backgroundcolor = "black";
    Box8.style.backgroundcolor = "black";
    Box9.style.backgroundcolor = "black";
   Box10.style.backgroundcolor = "black";
   Box11.style.backgroundcolor = "black";
   Box12.style.backgroundcolor = "black";

}



function GenerateNum(){
    let  num1 = (Math.random()*11)+1;
    let Num =  num1.toFixed(0)
console.log(Num)
    MainWork(Num);
    RandomNumber(Num);
}

 let p ;
function RandomNumber(HeyIne){
p = HeyIne;
    console.log("Number is "+p);
    return HeyIne;
}

function GameOverText(){
    Start_Over.innerText = "Aaahhhhh!! You Lost The Game"
    RuleOne.innerText = "Please Click To The New Game Button & Play Again"
    RuleTwo.innerText = 'The Number is '+p;
    RuleOne.style.color = "black"
    RuleOne.style.fontSize = "1.5em";
    RuleTwo.style.color = "red"
    RuleTwo.style.fontSize = "1.3em";
}

function WonMatch(){
    Start_Over.innerText = "!! Wooooohooooo YOU WON THE MATCH !!"
    RuleOne.innerText = "You Choose The Correct Number Boyy"
    RuleTwo.innerText = "You Are Winner!!!!!"
    RuleOne.style.color = "Red"
    RuleOne.style.fontSize = "1.5em";
    RuleTwo.style.color = "green"
    RuleTwo.style.fontSize = "1.5em";
}

function BoxFreeze(){
    Box.style.color = "red";
    Box2.style.color = "red";
    Box3.style.color = "red";
    Box4.style.color = "red";
    Box5.style.color = "red";
    Box6.style.color = "red";
    Box7.style.color = "red";
    Box8.style.color = "red";
    Box9.style.color = "red";
    Box10.style.color = "red";
    Box11.style.color = "red";
    Box12.style.color = "red";
    Box.style.backgroundcolor = "red";
    Box2.style.backgroundcolor = "red";
    Box3.style.backgroundcolor = "red";
    Box4.style.backgroundcolor = "red";
    Box5.style.backgroundcolor = "red";
    Box6.style.backgroundcolor = "red";
    Box7.style.backgroundcolor = "red";
    Box8.style.backgroundcolor = "red";
    Box9.style.backgroundcolor = "red";
    Box10.style.backgroundcolor = "red";
    Box11.style.backgroundcolor = "red";
    Box12.style.backgroundcolor = "red";
}

function MainWork(Num){
        Box.addEventListener("click", () => {
            if(Num === '1'){
            Box.style.color = "Yellow";
            Box.style.backgroundcolor = "red";
            WonMatch()
        }else{
                GameOverText();
                BoxFreeze();
        }});
        Box2.addEventListener("click", () => {
            if(Num === '2'){
            Box2.style.color = "Yellow";
            Box2.style.backgroundcolor = "red";
            WonMatch()
     }else{
        GameOverText();
        BoxFreeze();
} });
        Box3.addEventListener("click", () => {
            if(Num === '3'){
            Box3.style.color = "Yellow";
            Box3.style.backgroundcolor = "red";
            WonMatch()
      }else{
        GameOverText();
        BoxFreeze();
}  });

        Box4.addEventListener("click", () => {
            if(Num === '4'){
            Box4.style.color = "Yellow";
            Box4.style.backgroundcolor = "red";
            WonMatch()
      }else{
        GameOverText();
        BoxFreeze();
}  });

        Box5.addEventListener("click", () => {
            if(Num === '5'){
            Box5.style.color = "Yellow";
            Box5.style.backgroundcolor = "red";
            WonMatch()
     }else{
        GameOverText();
        BoxFreeze();
} });

        Box6.addEventListener("click", () => {
            if(Num === '6'){
            Box6.style.color = "Yellow";
            Box6.style.backgroundcolor = "red";
            WonMatch()
       }else{
        GameOverText();
        BoxFreeze();
}   });
   
        Box7.addEventListener("click", () => {
            if(Num === '7'){
            Box7.style.color = "Yellow";
            Box7.style.backgroundcolor = "red";
            WonMatch()
    }else{
        GameOverText();
        BoxFreeze();
}});
     
        Box8.addEventListener("click", () => {
            if(Num === '8'){
            Box8.style.color = "Yellow";
            Box8.style.backgroundcolor = "red";
            WonMatch()
      }else{
        GameOverText();
        BoxFreeze();
}  });
    
        Box9.addEventListener("click", () => {
            if(Num === '9'){
            Box9.style.color = "Yellow";
            Box9.style.backgroundcolor = "red";
            WonMatch()
      }else{
        GameOverText();
        BoxFreeze();
}  });
  
        Box10.addEventListener("click", () => {
            if(Num === '10'){
            Box10.style.color = "Yellow";
            Box10.style.backgroundcolor = "red";
            WonMatch()
      }else{
        GameOverText();
        BoxFreeze();
}  });

        Box11.addEventListener("click", () => {
            if(Num === '11'){
            Box11.style.color = "Yellow";
            Box11.style.backgroundcolor = "red";
            WonMatch()
      }else{
        GameOverText();
        BoxFreeze();
}  });
    
        Box12.addEventListener("click", () => {
            if(Num === '12'){
            Box12.style.color = "Yellow";
            Box12.style.backgroundcolor = "red";
            WonMatch()
        }else{
            GameOverText();
            BoxFreeze();
    }    });
}

